Revert "Remove RMM/RAFT dependencies, Part 1 (#195)" (#213)
#195 broke the cuML CI:
https://github.com/NVIDIA/cuml/actions/runs/34231441404/job/102085231790
```
FAILED integration/test_rf_regressor.py::test_rf_sample_weight_reg[False] - FutureWarning: `handle` parameter is deprecated and will be removed in 26.12. Please use `stream` instead
```

Let's revert #195 for now to unblock the cuML CI. I will try to figure
out the root cause.